version: "3.4"

services:
  pnl:
    environment:
      # - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://8081;http://+8080"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
