version: "3.7"

services:
  pnl:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    volumes:
      - ~/.aspnet/https:/https:ro
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "8080:8080"
  #     - "443:443"
  #   links:
  #     - pnl
  #   restart: always
  #   environment:
  #     DOMAINS: "devpnl.app -> http://pnl:5000"
  #     STAGE: "production"
