version: "3.7"

services:
  pnl:
    environment:
      - ASPNETCORE_ENVIRONMENT=Prodution
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ~/.aspnet/https:/https:ro
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - pnl
    restart: always
    environment:
      DOMAINS: "devpnl.app -> http://pnl:5000"
      STAGE: "production"
