version: "3.4"

services:
  db:
    image: dioscarr/mssql:2019
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  pnl:
    image: dioscarr/pnl:linux
    container_name: pnl
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
