version: "3.4"

services:
  db:
    image: dioscarr/mssql:2019
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  pnl:
    image: dioscarr/pnl:linux
    container_name: pnl
    # ports:
    #   - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "5000:5000"
      - "443:443"
    links:
      - pnl
    restart: always
    environment:
      DOMAINS: "devpnl.app -> http://pnl:5000"
      STAGE: "production"
