version: "3.4"

services:
  db:
    image: dioscarr/mssql:2019
    container_name: dbmssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
      ports:
        - "1433:1433"
      volumes:
        - /var/lib/mssql

  pnl:
    image: dioscarr/pnl:linux
    container_name: app
    # ports:
    #   - "8000:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - pnl
    restart: always
    environment:
      DOMAINS: "devpnl.app -> http://app:5000"
      STAGE: "production"
