version: "3.4"

services:
  db:
    image: devpnl.azurecr.io/mssql:2019
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  pnl:
    image: ${DOCKER_REGISTRY-}pnl
    container_name: app
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
