version: "3.7"

services:
  db:
    image: dioscarr/mssql:2019
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-volume:/var/opt/mssql
      # - /storage/backup:/backup
    # networks:
    #   - default
  pnl:
    image: dioscarr/pnl:linux
    container_name: pnl
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  # backup:
  #   image: dioscarr/mssql:2019bk
  #   # for using the cleanup feature, use the backup volume from db.
  #   # volumes:
  #   #   - /storage/backup:/backup
  #   environment:
  #     - DB_SERVER=db
  #     - DB_USER=SA
  #     - DB_PASSWORD=Password@123
  #     - "DB_NAMES= MyFirstDatabaseToRestore MySecondDatabaseToRestore"
  #     - CRON_SCHEDULE=0 1 * * *
  #   networks:
  #     - default
volumes:
  mssql-volume:
