version: "3.4"

services:
  db:
    image: dioscarr/mssql:2019
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  pnl:
    image: dioscarr/pnl:linux
    container_name: app
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     #- ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - pnl
  #   restart: always
  #   environment:
  #     DOMAINS: "devpnl.com -> http://pnl:5000"
  #     STAGE: "production"
