version: "3.4"

services:
  pnl:
    image: ${DOCKER_REGISTRY-}pnl
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
